apiVersion: v2
name: immich
version: 0.1.0

dependencies:
- name: immich
  version: "0.10.3"
  repository: https://immich-app.github.io/immich-charts
- name: cloudnative-pg
  version: "0.27.0"
  repository: https://cloudnative-pg.io/charts/
