apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: whoami
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.argocdProjName }}
  source:
    path: k8s/whoami
    repoURL: https://github.com/schemmeltobi/homeserver
    targetRevision: HEAD
