apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer
  labels:
    app: portainer
spec:
  entryPoints:
    - websecure
  routes:
    - match: {{ printf "Host(`%s`)" .Values.server.domain }}
      kind: Rule
      services:
      - name: portainer
        port: 9000
  tls:
    certResolver: letsencrypt