apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-db
spec:
  instances: 1

  storage:
    size: 1Gi
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-minimal-trixie
    major: 18
