apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/cloudnative-pg/artifacts/refs/heads/main/image-catalogs/catalog-minimal-trixie.yaml # https://cloudnative-pg.io/docs/1.28/image_catalog#cloudnativepg-catalogs
  - db.yaml
  - redis.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
